# Generated by Django 2.0.2 on 2018-03-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=250)),
                ('brand_status', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=250)),
                ('category_status', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('inventory_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_order_total', models.FloatField()),
                ('inventory_order_date', models.DateField()),
                ('inventory_order_name', models.CharField(max_length=255)),
                ('inventory_order_address', models.TextField()),
                ('payment_status', models.CharField(max_length=6)),
                ('inventory_order_status', models.CharField(max_length=100)),
                ('inventory_order_created_date', models.DateField()),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('inventory_order_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('tax', models.FloatField()),
            ],
            options={
                'db_table': 'order_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=300)),
                ('product_description', models.TextField()),
                ('product_quantity', models.IntegerField()),
                ('product_unit', models.CharField(max_length=150)),
                ('product_base_price', models.FloatField()),
                ('product_tax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('product_minimum_order', models.FloatField()),
                ('product_enter_by', models.IntegerField()),
                ('product_status', models.CharField(max_length=8)),
                ('product_date', models.DateField()),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('user_type', models.CharField(max_length=6)),
                ('user_status', models.CharField(max_length=8)),
                ('user_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
